#!/usr/bin/env bash
# Create the Cloudflare Tunnel for dev.site and point DNS at it.
#
# Two ways to authenticate, in order of preference:
#
#   1. CLOUDFLARE_API_TOKEN — fully headless. Needs Account > Cloudflare Tunnel > Edit and
#      Zone > DNS > Edit on the dev.site zone.
#   2. `cloudflared tunnel login` — opens a browser and writes ~/.cloudflared/cert.pem.
#
# Idempotent either way: re-running adopts an existing tunnel and repoints the records.
set -euo pipefail

DEVSITE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export DEVSITE_ROOT
# shellcheck source=./env
source "$DEVSITE_ROOT/deploy/env"

api() {
  local method="$1" path="$2"; shift 2
  curl -sS -X "$method" "https://api.cloudflare.com/client/v4$path" \
    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    -H "Content-Type: application/json" "$@"
}

# Fail loudly on an API error rather than letting a null id flow into a config file.
check() {
  python3 -c '
import json, sys
body = sys.stdin.read()
try:
    data = json.loads(body)
except Exception:
    sys.exit(f"cloudflare returned non-JSON: {body[:200]}")
if not data.get("success"):
    errors = "; ".join(f'"'"'{e.get("code")}: {e.get("message")}'"'"' for e in data.get("errors", []))
    sys.exit(f"cloudflare API error: {errors or body[:200]}")
print(json.dumps(data["result"]))
'
}

write_config() {
  local tunnel_id="$1" credentials="$2"
  cat > "$DEVSITE_ROOT/deploy/cloudflared.yml" <<EOF
# Generated by deploy/setup-tunnel.sh — safe to regenerate.
tunnel: $tunnel_id
credentials-file: $credentials

ingress:
  - hostname: $DEVSITE_HOSTNAME
    service: http://$DEVSITE_BIND
  - hostname: www.$DEVSITE_HOSTNAME
    service: http://$DEVSITE_BIND
  # cloudflared requires a catch-all; anything unmatched above is refused.
  - service: http_status:404
EOF
  echo "wrote deploy/cloudflared.yml"
}

# ---------------------------------------------------------------- API token path

if [[ -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then
  echo "authenticating with CLOUDFLARE_API_TOKEN"

  account_id="$(api GET "/zones/$CLOUDFLARE_ZONE_ID" | check \
    | python3 -c 'import json,sys; print(json.load(sys.stdin)["account"]["id"])')"
  echo "account: $account_id"

  existing="$(api GET "/accounts/$account_id/cfd_tunnel?name=$DEVSITE_TUNNEL_NAME&is_deleted=false" \
    | check | python3 -c 'import json,sys; r=json.load(sys.stdin); print(r[0]["id"] if r else "")')"

  credentials="$HOME/.cloudflared/$DEVSITE_TUNNEL_NAME.json"
  mkdir -p "$HOME/.cloudflared"

  if [[ -n "$existing" ]]; then
    tunnel_id="$existing"
    echo "tunnel '$DEVSITE_TUNNEL_NAME' already exists: $tunnel_id"
    if [[ ! -f "$credentials" ]]; then
      cat >&2 <<EOF
error: the tunnel exists but $credentials is missing.

  A tunnel's secret is only returned when it is created. Either restore that file, or
  delete the tunnel and re-run:

      curl -X DELETE "https://api.cloudflare.com/client/v4/accounts/$account_id/cfd_tunnel/$tunnel_id" \\
        -H "Authorization: Bearer \$CLOUDFLARE_API_TOKEN"
EOF
      exit 1
    fi
  else
    echo "creating tunnel '$DEVSITE_TUNNEL_NAME'"
    secret="$(head -c 32 /dev/urandom | base64)"
    tunnel_id="$(api POST "/accounts/$account_id/cfd_tunnel" \
      --data "$(python3 -c "import json,sys; print(json.dumps({'name': sys.argv[1], 'tunnel_secret': sys.argv[2], 'config_src': 'local'}))" "$DEVSITE_TUNNEL_NAME" "$secret")" \
      | check | python3 -c 'import json,sys; print(json.load(sys.stdin)["id"])')"

    # cloudflared reads the secret from here; it is never retrievable from the API again.
    umask 077
    python3 -c "
import json, sys
json.dump({'AccountTag': sys.argv[1], 'TunnelID': sys.argv[2], 'TunnelSecret': sys.argv[3]}, open(sys.argv[4], 'w'))
" "$account_id" "$tunnel_id" "$secret" "$credentials"
    echo "tunnel created: $tunnel_id"
    echo "credentials written to $credentials — back this up, it cannot be re-fetched"
  fi

  write_config "$tunnel_id" "$credentials"

  # Proxied CNAME to the tunnel. Cloudflare resolves *.cfargotunnel.com internally; it
  # never appears in public DNS.
  for host in "$DEVSITE_HOSTNAME" "www.$DEVSITE_HOSTNAME"; do
    record_id="$(api GET "/zones/$CLOUDFLARE_ZONE_ID/dns_records?name=$host" | check \
      | python3 -c 'import json,sys; r=json.load(sys.stdin); print(r[0]["id"] if r else "")')"
    payload="$(python3 -c "
import json, sys
print(json.dumps({'type': 'CNAME', 'name': sys.argv[1], 'content': sys.argv[2] + '.cfargotunnel.com',
                  'proxied': True, 'ttl': 1, 'comment': 'dev.site control plane via cloudflared'}))
" "$host" "$tunnel_id")"

    if [[ -n "$record_id" ]]; then
      api PUT "/zones/$CLOUDFLARE_ZONE_ID/dns_records/$record_id" --data "$payload" | check > /dev/null
      echo "updated DNS record for $host"
    else
      api POST "/zones/$CLOUDFLARE_ZONE_ID/dns_records" --data "$payload" | check > /dev/null
      echo "created DNS record for $host"
    fi
  done

  echo
  echo "done. start everything with:  ./deploy/run.sh"
  exit 0
fi

# ------------------------------------------------------------ browser login path

if [[ ! -f "$HOME/.cloudflared/cert.pem" ]]; then
  cat >&2 <<'EOF'
error: no Cloudflare credentials found.

  Either export an API token with Account > Cloudflare Tunnel > Edit and
  Zone > DNS > Edit:

      export CLOUDFLARE_API_TOKEN=...
      ./deploy/setup-tunnel.sh

  Or authorize this machine through a browser:

      cloudflared tunnel login
      ./deploy/setup-tunnel.sh
EOF
  exit 1
fi

if cloudflared tunnel list --output json | grep -q "\"name\":\"$DEVSITE_TUNNEL_NAME\""; then
  echo "tunnel '$DEVSITE_TUNNEL_NAME' already exists, reusing it"
else
  echo "creating tunnel '$DEVSITE_TUNNEL_NAME'"
  cloudflared tunnel create "$DEVSITE_TUNNEL_NAME"
fi

tunnel_id="$(cloudflared tunnel list --output json \
  | python3 -c "import json,sys;print(next(t['id'] for t in json.load(sys.stdin) if t['name']=='$DEVSITE_TUNNEL_NAME'))")"
credentials="$HOME/.cloudflared/$tunnel_id.json"
[[ -f "$credentials" ]] || { echo "error: missing credentials at $credentials" >&2; exit 1; }

write_config "$tunnel_id" "$credentials"

cloudflared tunnel route dns --overwrite-dns "$DEVSITE_TUNNEL_NAME" "$DEVSITE_HOSTNAME"
cloudflared tunnel route dns --overwrite-dns "$DEVSITE_TUNNEL_NAME" "www.$DEVSITE_HOSTNAME"

echo
echo "done. start everything with:  ./deploy/run.sh"
