[package]
name = "devsite-web"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
devsite-client.workspace = true
devsite-proto.workspace = true
iroh = { version = "1", default-features = false, features = ["tls-ring"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
tracing.workspace = true
tracing-subscriber-wasm = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
getrandom = { version = "0.3", features = ["wasm_js"] }
data-encoding.workspace = true
